name: snipedashx

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run fetch script
        run: node fetch.js

      - name: Commit changes if any
        run: |
          git config --global user.name "snipe-x"
          git config --global user.email "snipe-x@noreply.github.com"

    
          if [[ `git status --porcelain` ]]; then
            git add emotes.json
            git commit -m "update emote list"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "No changes to commit."
          fi
